from __future__ import annotations

from pathlib import Path
from typing import Any, Collection, Mapping, Protocol


class HarnessRuntime(Protocol):
    """Typed dependency surface that harness.py provides to harness_core.

    This Protocol is the single source of truth for what the core modules may
    consume from the harness facade. Core functions annotate their ``ctx``
    parameter as ``HarnessRuntime``; a static type checker (pyright) then
    verifies every ``ctx.<member>(...)`` access against these real signatures,
    catching typos, wrong argument counts, and signature drift between
    harness.py and the core *before* the code runs.

    The concrete runtime carrier is :class:`HarnessContext`, built from the
    harness module namespace via :meth:`HarnessContext.from_namespace`. The
    carrier is intentionally dynamic (any missing member reads back as ``None``)
    so partial contexts in unit tests stay valid; the *contract* is here.

    The members below were transcribed from the live, resolved signatures of the
    harness.py facade (``inspect.signature`` over the bound namespace), so they
    reflect exactly what the harness exposes -- not an idealized approximation.
    """

    # --- constants ---
    AI_DIR: Path
    DOCS_DIR: Path
    HARNESS_CONFIG_PATH: Path
    HISTORY_DIR: Path
    PC_CANDIDATES_PATH: Path
    PROJECT_CONFIG_PATH: Path
    PROJECT_CONTRACT_PATH: Path
    PROJECT_DIR: Path
    ROOT: Path

    DEFAULT_MODEL_POLICY: dict[str, Any]
    DEFAULT_PROVIDER_CAPABILITIES: dict[str, Any]
    DEFAULT_PROVIDER_COMMANDS: dict[str, Any]
    PERFORMANCE_PROFILES: dict[str, Any]
    PROVIDER_BY_MODEL: dict[str, str]
    STAGE_OUTPUTS: dict[str, str]

    DEFAULT_PERFORMANCE: str
    PC_PENDING_STATUS: str
    PC_PROJECT_WIDE_SCOPE: str
    PC_REVIEW_STAGE: str
    PIPELINE_MODE: str
    PLAN_STAGE: str
    PLAN_SCHEMAS_REQUIRED: bool
    SCHEMAS_CONFORMANCE_REQUIRED: bool
    START_STAGE: str
    DEVELOP_STAGE: str
    VERIFY_STAGE: str
    DOCUMENT_STAGE: str
    VERIFY_RETRY_TARGET_STAGE: str

    DEFAULT_PROVIDER_HEARTBEAT_SECONDS: int
    DEFAULT_VERIFY_COMMAND_TIMEOUT_SECONDS: int
    HISTORY_SCHEMA_VERSION: int
    PC_CANDIDATES_SCHEMA_VERSION: int

    PROVIDERS: tuple[str, ...]
    STAGES: list[str]
    NO_COMMIT_STAGES: Collection[str]

    # --- callables (signatures mirror the harness.py facade) ---
    def apply_performance_to_command(self, provider: str, command: list[str], performance: Any | None) -> list[str]: ...
    def assert_no_incomplete_runs_for_new_run(self) -> None: ...
    def assert_prev_run_branch_merged(self) -> None: ...
    def available_providers(self) -> list[str]: ...
    def boolish(self, value: Any) -> bool: ...
    def build_provider_schedule(self, state: dict[str, Any]) -> dict[str, str]: ...
    def candidate_providers_for_stage(self, stage: str, policy: dict[str, Any], available: list[str]) -> list[str]: ...
    def color_text(self, text: str, *styles: str) -> str: ...
    def compact_history_text(self, value: Any, max_len: int = 240) -> str: ...
    def compute_provider_schedule(self, state: dict[str, Any], *, strict_independence: bool) -> dict[str, str] | None: ...
    def config_path(self) -> Path: ...
    def configured_verification_commands(self, feature: str) -> tuple[list[dict[str, Any]], bool]: ...
    def display_cwd(self, path: Path) -> str: ...
    def enforce_harness_verify_result(self, state: dict[str, Any], result: dict[str, Any], status: str, next_stage: str) -> tuple[str, str]: ...
    def ensure_dirs(self) -> None: ...
    def ensure_project_contract_file(self) -> None: ...
    def ensure_provider_schedule(self, state: dict[str, Any], *, persist: bool = True, console: bool = False, record_event: bool = True) -> dict[str, str]: ...
    def execute_current_prompt(self, state: dict[str, Any], timeout_seconds: int) -> dict[str, Any]: ...
    def expand_runtime_placeholders(self, value: Any, feature: str) -> str: ...
    def expected_docx_path(self, feature: str) -> Path: ...
    def extract_feature_name(self, spec_text: str) -> str | None: ...
    def extract_project_contract_candidates(self, state: dict[str, Any]) -> dict[str, Any]: ...
    def feature_dir(self, feature: str) -> Path: ...
    def feature_schemas_path(self, feature: str) -> Path: ...
    def file_hash(self, path: Path) -> str: ...
    def file_policy_snapshot(self, feature: str) -> dict[str, str]: ...
    def file_size(self, path: Path) -> int: ...
    def filtered_changed_paths(self, state: dict[str, Any], stage: str) -> list[str]: ...
    def find_stage_result(self, text: str) -> dict[str, Any]: ...
    def format_bytes(self, size: int) -> str: ...
    def format_duration(self, seconds: float) -> str: ...
    def generate_prompt(self, state: dict[str, Any], stage: str, retry_context: str | None = None) -> Path: ...
    def git_add(self, paths: list[str]) -> None: ...
    def git_changed_paths(self) -> list[str]: ...
    def git_commit(self, message: str, amend: bool = False) -> str: ...
    def git_head(self) -> str: ...
    def git_show_file(self, ref: str, rel_path: str) -> bytes | None: ...
    def current_branch(self) -> str: ...
    def branch_exists(self, name: str) -> bool: ...
    def checkout_new_branch(self, name: str) -> None: ...
    def branch_is_merged(self, branch: str, base: str) -> bool: ...
    def merge_tree_conflicts(self, base: str, branch: str) -> "list[str] | None": ...
    def history_list(self, value: Any, max_items: int = 40) -> list[str]: ...
    def history_object_list(self, value: Any, title_keys: list[str], max_items: int = 40) -> list[dict[str, Any]]: ...
    def is_production_code_path(self, path: str) -> bool: ...
    def is_test_path(self, path: str) -> bool: ...
    def iso_now(self) -> str: ...
    def known_provider_names(self) -> list[str]: ...
    def latest_code_writer(self, assignments: dict[str, str], stages: list[str]) -> str | None: ...
    def latest_verification_result_path(self, feature: str) -> Path: ...
    def load_config(self) -> dict[str, Any]: ...
    def load_project_config(self) -> dict[str, Any]: ...
    def load_state(self, feature: str) -> dict[str, Any]: ...
    def log_event(self, state: dict[str, Any], event: str, message: str, *, stage: str | None = None, console: bool = True, **fields: Any) -> None: ...
    def markdown_section_items(self, text: str, heading_needles: list[str], max_items: int = 20) -> list[str]: ...
    def model_policy(self) -> dict[str, Any]: ...
    def norm_repo_path(self, path: str) -> str: ...
    def normalize_performance(self, value: Any | None) -> str: ...
    def now_stamp(self) -> str: ...
    def ordered_unique(self, values: list[str] | tuple[str, ...]) -> list[str]: ...
    def parse_result_json_from_text(self, text: str) -> dict[str, Any]: ...
    def pc_candidates_path(self) -> Path: ...
    def performance_profile(self, value: Any | None) -> dict[str, dict[str, str]]: ...
    def pipeline_extracts_pc_candidates(self, pipeline_mode: Any) -> bool: ...
    def prepare_provider_command(self, provider: str, prompt_text: str | None = None, prompt_file: Path | None = None, log_file: Path | None = None, performance: Any | None = None) -> tuple[list[str], bool]: ...
    def preset_provider_for_stage(self, stage: str) -> str | None: ...
    def project_config_path(self) -> Path: ...
    def project_contract_prompt_text(self) -> str: ...
    def prompt_path(self, state: dict[str, Any], stage: str) -> Path: ...
    def provider_available(self, provider: str) -> bool: ...
    def provider_capabilities(self, provider: str) -> set[str]: ...
    def provider_command(self, provider: str) -> list[str]: ...
    def provider_config(self, provider: str) -> dict[str, Any]: ...
    def provider_enabled(self, provider: str) -> bool: ...
    def provider_failure_reason(self, state: dict[str, Any], *, stage: str, provider: str, failure: str, stdout_path: Path, stderr_path: Path, provider_log_path: Path) -> str: ...
    def provider_for_stage(self, stage: str, state: dict[str, Any] | None = None) -> str: ...
    def provider_order_for_role(self, stage: str, role: str, policy: dict[str, Any]) -> list[str]: ...
    def provider_performance_settings(self, provider: str, performance: Any | None) -> dict[str, str]: ...
    def provider_schedule_stages(self, state: dict[str, Any]) -> list[str]: ...
    def raw_provider_command(self, provider: str) -> list[str]: ...
    def read_json_file(self, path: Path, default: Any) -> Any: ...
    def read_preset(self, stage: str) -> tuple[dict[str, Any], str, str]: ...
    def read_stage_result_json(self, path: Path) -> dict[str, Any]: ...
    def record_project_history(self, state: dict[str, Any]) -> dict[str, Any]: ...
    def redact_prompt_command(self, command: list[str], prompt_text: str | None) -> list[str]: ...
    def rel(self, path: Path) -> str: ...
    def resolve_executable(self, command: list[str]) -> str | None: ...
    def run_dir(self, feature: str) -> Path: ...
    def run_harness_verification(self, state: dict[str, Any], stage_result: dict[str, Any] | None = None) -> dict[str, Any]: ...
    def run_text_provider_prompt(self, provider: str, prompt_text: str, *, logs_dir: Path, log_prefix: str, timeout_seconds: int = 3600, performance: Any | None = None) -> dict[str, Any]: ...
    def safe_git_head(self) -> str: ...
    def save_state(self, state: dict[str, Any]) -> None: ...
    def should_extract_pc_candidates(self, state: dict[str, Any]) -> bool: ...
    def slugify(self, text: str) -> str: ...
    def stage_default_next(self, stage: str) -> str | None: ...
    def stage_output_path(self, feature: str, stage: str) -> Path: ...
    def stage_provider_score(self, stage: str, provider: str, candidates: list[str], assignments: dict[str, str], ordered_stages: list[str], policy: dict[str, Any]) -> int: ...
    def stage_result_json_path(self, feature: str, stage: str) -> Path: ...
    def stage_role(self, stage: str) -> str: ...
    def stage_status(self, result: dict[str, Any]) -> str: ...
    def state_path(self, feature: str) -> Path: ...
    def suggested_retry_command(self, state: dict[str, Any], *, auto: bool = True) -> str: ...
    def validate_deep_thinking_ready(self, state: dict[str, Any] | None = None) -> dict[str, Any]: ...
    def validate_docx_file(self, path: Path) -> str | None: ...
    def validate_feature_schemas(self, feature: str) -> str | None: ...
    def validate_feature_schemas_conformance(self, feature: str) -> "tuple[str | None, list[str]]": ...
    def validate_slug(self, slug: str) -> bool: ...
    def verification_dir(self, feature: str) -> Path: ...
    def warn_pending_pc_candidates_for_new_run(self) -> None: ...
    def write_handoff(self, state: dict[str, Any], reason: str, *, stage: str | None = None, next_action: str | None = None, result: dict[str, Any] | None = None) -> Path: ...
    def write_json_file(self, path: Path, value: Any) -> None: ...
    def write_policy_violations(self, state: dict[str, Any], stage: str) -> list[str]: ...
    def write_project_config(self, config: dict[str, Any]) -> None: ...


def _runtime_member_names() -> frozenset[str]:
    """Member names the carrier accepts -- derived solely from HarnessRuntime so
    the Protocol stays the single source of truth (constants live in
    ``__annotations__``; callables show up as public attributes via ``dir``)."""
    names = set(getattr(HarnessRuntime, "__annotations__", {}))
    names.update(name for name in dir(HarnessRuntime) if not name.startswith("_"))
    return frozenset(names)


_KNOWN_MEMBERS = _runtime_member_names()


class HarnessContext:
    """Dynamic runtime carrier implementing :class:`HarnessRuntime`.

    Constructed from harness.py's module namespace (constants + facade
    functions). Only declared HarnessRuntime members are retained; any member
    not supplied reads back as ``None`` via ``__getattr__`` so partial contexts
    (e.g. in unit tests) remain valid. The typed contract -- and the only thing
    consumers should rely on -- is HarnessRuntime; this class is just the bag of
    bound values. The ``__getattr__`` fallback also makes the carrier
    structurally satisfy HarnessRuntime for the type checker.
    """

    def __init__(self, **values: Any) -> None:
        self.__dict__.update(values)

    @classmethod
    def from_namespace(cls, ns: Mapping[str, Any]) -> "HarnessContext":
        """Build a context from any name->value mapping, keeping only declared
        HarnessRuntime members and ignoring everything else."""
        return cls(**{key: value for key, value in ns.items() if key in _KNOWN_MEMBERS})

    def __getattr__(self, name: str) -> Any:
        # Reached only for declared members that were never supplied; mirrors the
        # historical all-optional context so partial test contexts stay valid.
        return None
